language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations accounts
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py runserver
